print('Введите местоположение коня: ')
x = float(input())
y = float(input())
print('Введите местоположение точки на доске: ')
x1 = float(input())
y1 = float(input())
x = int(x*10)
y = int(y*10)
x1 = int(x1*10)
y1 = int(y1* 10)
print(f'Конь в клетке {x, y}. Точка в клетке {x1, y1}.')
if abs((x - x1) * (y - y1)) == 2:
    print('Конь не может ходить в эту точку.')
else:
    print('Конь может ходить в эту точку.')